### ISSUE TITLE
Regarding ADS131M08 library

### ISSUE THREAD

**Issue by Dayanand1996** [mcjun37/stm32f7_ads131e08_example#1]
would this library work for ADS131M08EVM ???? if not please upload the ADS131M08EVM library to communicate with STM32G071RBT6

**Comment by mcjun37** [comment]
Hi, Dayanand.

First of all, thanks for visiting my repository. 
I made the library for ads131e08 2 years ago.
So, I cannot know whether this library works for ads131m08 or not. But I think it will need a small modification, like registers related to setting ADC.

Best regards,
minchul

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-03-24 (금) 22:31:51 (GMT+09:00)
Subject: [mcjun37/ads131e08] Regarding ADS131M08 library (Issue #1)

would this library work for ADS131M08EVM ???? if not please upload the ADS131M08EVM library to communicate with STM32G071RBT6

**Comment by Dayanand1996** [comment]
Thank you sir for your reply,
  Can you please help in achieving the SPI communication between stm32g071
amd ADS131M08/ADS131E08EVM with .ioc file

Regards
Dayanand

**Comment by mcjun37** [comment]
Sorry, I did not use EVM for ads131e08.
But you can archive the SPI interface by changing the pin map in STM CUBE little bit.
I hope your good luck.

Best regards,
minchul

-----Original Message-----
